# Generated by Django 3.2.10 on 2022-07-07 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='douluo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='标题')),
                ('content', models.CharField(max_length=254, verbose_name='正文')),
                ('link', models.CharField(max_length=64, verbose_name='链接')),
            ],
        ),
    ]
