# Generated by Django 3.2.10 on 2022-07-08 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novelweb', '0002_alter_douluo_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='tsxk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='标题')),
                ('content', models.TextField(verbose_name='正文')),
                ('link', models.CharField(max_length=64, verbose_name='链接')),
            ],
        ),
    ]
